services:
  server:
    container_name: server
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/logs:/app/logs
    networks:
      - app-network

  client:
    container_name: client
    build: ./client
    depends_on:
      - server
    env_file:
      - ./client/.env
    volumes:
      - ./client/data:/app/data
      - ./client/logs:/app/logs
    networks:
      - app-network
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge